/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing User.
 */
export interface User {
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
  /**
   * User Status
   */
  userStatus?: number;
}

/**
 * An interface representing Category.
 */
export interface Category {
  id?: number;
  name?: string;
}

/**
 * An interface representing Tag.
 */
export interface Tag {
  id?: number;
  name?: string;
}

/**
 * A group of properties representing a pet.
 * @summary A pet
 */
export interface Pet {
  /**
   * The id of the pet. A more detailed description of the id of the pet.
   */
  id?: number;
  category?: Category;
  name: string;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store. Possible values include: 'available', 'pending', 'sold'
   */
  status?: Status;
}

/**
 * An interface representing Order.
 */
export interface Order {
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: Date;
  /**
   * Order Status. Possible values include: 'placed', 'approved', 'delivered'
   */
  status?: Status1;
  complete?: boolean;
}

/**
 * An interface representing SwaggerPetstoreOptions.
 */
export interface SwaggerPetstoreOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreAddPetUsingByteArrayOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Pet object in the form of byte array
   */
  body?: string;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreAddPetOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Pet object that needs to be added to the store
   */
  body?: Pet;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreUpdatePetOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Pet object that needs to be added to the store
   */
  body?: Pet;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreFindPetsByStatusOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Status values that need to be considered for filter. Default value: available.
   */
  status?: string[];
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreFindPetsByTagsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Tags to filter by
   */
  tags?: string[];
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreUpdatePetWithFormOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Updated name of the pet
   */
  name?: string;
  /**
   * Updated status of the pet
   */
  status?: string;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreDeletePetOptionalParams extends msRest.RequestOptionsBase {
  apiKey?: string;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreUploadFileOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Additional data to pass to server
   */
  additionalMetadata?: string;
  /**
   * file to upload
   */
  file?: msRest.HttpRequestBody;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstorePlaceOrderOptionalParams extends msRest.RequestOptionsBase {
  /**
   * order placed for purchasing the pet
   */
  body?: Order;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreCreateUserOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Created user object
   */
  body?: User;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreCreateUsersWithArrayInputOptionalParams extends msRest.RequestOptionsBase {
  /**
   * List of user object
   */
  body?: User[];
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreCreateUsersWithListInputOptionalParams extends msRest.RequestOptionsBase {
  /**
   * List of user object
   */
  body?: User[];
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreLoginUserOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The user name for login
   */
  username?: string;
  /**
   * The password for login in clear text
   */
  password?: string;
}

/**
 * Optional Parameters.
 */
export interface SwaggerPetstoreUpdateUserOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Updated user object
   */
  body?: User;
}

/**
 * Defines values for Status.
 * Possible values include: 'available', 'pending', 'sold'
 * @readonly
 * @enum {string}
 */
export type Status = 'available' | 'pending' | 'sold';

/**
 * Defines values for Status1.
 * Possible values include: 'placed', 'approved', 'delivered'
 * @readonly
 * @enum {string}
 */
export type Status1 = 'placed' | 'approved' | 'delivered';

/**
 * Contains response data for the findPetsByStatus operation.
 */
export type FindPetsByStatusResponse = Array<Pet> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Pet[];
    };
};

/**
 * Contains response data for the findPetsByTags operation.
 */
export type FindPetsByTagsResponse = Array<Pet> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Pet[];
    };
};

/**
 * Contains response data for the findPetsWithByteArray operation.
 */
export type FindPetsWithByteArrayResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
};

/**
 * Contains response data for the getPetById operation.
 */
export type GetPetByIdResponse = Pet & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Pet;
    };
};

/**
 * Contains response data for the getInventory operation.
 */
export type GetInventoryResponse = {
  /**
   * The response body properties.
   */
  [propertyName: string]: number;
} & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: { [propertyName: string]: number };
    };
};

/**
 * Contains response data for the placeOrder operation.
 */
export type PlaceOrderResponse = Order & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Order;
    };
};

/**
 * Contains response data for the getOrderById operation.
 */
export type GetOrderByIdResponse = Order & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Order;
    };
};

/**
 * Contains response data for the loginUser operation.
 */
export type LoginUserResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
};

/**
 * Contains response data for the getUserByName operation.
 */
export type GetUserByNameResponse = User & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: User;
    };
};
